### PR TITLE
Swagger and ddt

### PR DESCRIPTION
**Pull request by XOBBIT1**

### CODE REVIEW

**Comment by XOBBIT1** [comment]
Я на выходных исправлю короч

**Review by ksendzovSL — CHANGES_REQUESTED** [review]

**Comment by ksendzovSL** [comment]
Got it
Now conflicts again :)

**Comment by XOBBIT1** [comment]
I did the conflicts by myself on that way. ) I'll fix it. About English, no problem )

**Comment by XOBBIT1** [comment]
didn't fixed (

**Comment by XOBBIT1** [comment]
fixed )

**Comment by ksendzovSL** [comment]
Good job!

**Pull request merged**
